// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "./Todo.res.mjs";
import * as React from "react";
import * as Button from "./Button.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

var initialState_todos = [];

var initialState = {
  newInputValue: "",
  todos: initialState_todos
};

function reducer(state, action) {
  if (typeof action !== "object") {
    return {
            newInputValue: "",
            todos: Belt_Array.concatMany([
                  state.todos,
                  [Todo.make(state.newInputValue)]
                ])
          };
  }
  switch (action.TAG) {
    case "Delete" :
        var id = action._0;
        return {
                newInputValue: state.newInputValue,
                todos: state.todos.filter(function (v) {
                      return v.id !== id;
                    })
              };
    case "ToggleDone" :
        var id$1 = action._0;
        return {
                newInputValue: state.newInputValue,
                todos: state.todos.map(function (todo) {
                      if (todo.id !== id$1) {
                        return todo;
                      } else {
                        return {
                                id: todo.id,
                                done: !todo.done,
                                label: todo.label
                              };
                      }
                    })
              };
    case "UpdatedInput" :
        return {
                newInputValue: action._0,
                todos: state.todos
              };
    
  }
}

function App(props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Todo List",
                      className: "text-3xl text-red-800 font-semibold"
                    }),
                JsxRuntime.jsx("input", {
                      className: "border-2 rounded-lg border-blue-500 p-1 mx-2 text-black",
                      value: state.newInputValue,
                      onChange: (function (e) {
                          dispatch({
                                TAG: "UpdatedInput",
                                _0: e.currentTarget.value
                              });
                        })
                    }),
                JsxRuntime.jsx(Button.make, {
                      children: "Add Todo",
                      onClick: (function (param) {
                          dispatch("Add");
                        })
                    }),
                state.todos.map(function (todo) {
                      return JsxRuntime.jsx("div", {
                                  children: todo.label,
                                  className: (
                                    todo.done ? "text-green-500" : "text-red-600"
                                  ) + " cursor-pointer",
                                  onClick: (function (param) {
                                      dispatch({
                                            TAG: "ToggleDone",
                                            _0: todo.id
                                          });
                                    }),
                                  onDoubleClick: (function (param) {
                                      dispatch({
                                            TAG: "Delete",
                                            _0: todo.id
                                          });
                                    })
                                });
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
