// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bacon from "./components/bacon.res.mjs";
import * as React from "react";
import * as Button from "./Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return "Loading";
      });
  var setBacon = match[1];
  var bacon = match[0];
  var handleBacon = function () {
    return Bacon.$$fetch().then(function (t) {
                return Promise.resolve(setBacon(function (param) {
                                return t;
                              }));
              });
  };
  React.useEffect((function () {
          handleBacon();
        }), []);
  React.useEffect((function () {
          console.log(bacon);
        }), [bacon]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Bacon Ipsum",
                      className: "text-3xl font-semibold mb-5"
                    }),
                JsxRuntime.jsx(Button.make, {
                      children: "refresh data",
                      onClick: (function (param) {
                          handleBacon();
                        })
                    }),
                Bacon.render(bacon)
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Bacon Not a pure module */
